### ISSUE TITLE
OK URLs marked as 404

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/clarin-curation-module#35]
I had a look at https://curate.acdh.oeaw.ac.at/'#!ResultView/statistics//Slovenian_language_resource_repository_CLARIN_SI/404
as https://curate.acdh.oeaw.ac.at/#!ResultView/collection//Slovenian_language_resource_repository_CLARIN_SI currently reports a stunning "Total number of broken links: 421".
Yet for all the URLs from the 404 list that I checked, the URL is correct and working.

**Comment by coy123** [comment]
I ran a couple of those links i through the link checker. They seemed to be returning 200. This means that during the time of the original checking, in this case 2018-11-17, the links were broken. When Link checker checks them again, it will update the results.

**Comment by TomazErjavec** [comment]
> This means that during the time of the original checking, in this case 2018-11-17, the links were broken.

This seems somewhat unlikely, as the links are static, and once the url was there it was, well, there. I can possibly imagine that the server was down, but then you would not get 404. 

> When Link checker checks them again, it will update the results.

Best to wait till that happens to see the results then. Any indication on when this will happen, i.e. when I should check again?

**Comment by coy123** [comment]
As we have more than 5 million urls to check, I can not say normally when the run will loop back. But I will try to prioritize the collection and will inform here when its done.

**Comment by kosarko** [comment]
for us (https://curate.acdh.oeaw.ac.at/'#!ResultView/statistics//LINDAT_CLARIN_digital_library_at_the_Institute_of_Formal_and_Applied_Linguistics_UFAL_Faculty_of_Mathematics_and_Physics_Charles_University/404) it reports 1809 404s; the ones that I've tried are working for me - I've picked like 15 at random.
Is there a way to get past the first 100 URLs limit?

I too would say if the servers are up you should not be getting 404 (if it works now), if they are down you'll get some 5xx error or timeout, if you are reaching our connection/request limit, you'll get 429

**Comment by coy123** [comment]
Ok, I found the culprit. There was a bug before, where URLs with query parameters (? in the url) would be handled wrong. I forgot to include the question mark when rebuilding the URLs. That caused link checker to check all the urls without the question mark in them, so thats why all the URLs returned 404. This bug has long been fixed but the Linkchecker hasn't run on these URLs since then. 

I will put the priority on 404 urls on linkchecker. I can't really tell how long it will take because we have ~738,000 "404" Urls. I will update this issue when its done.

> Is there a way to get past the first 100 URLs limit?

This is a planned feature but not implemented yet. You can open a new issue if you want and follow it from there.

**Comment by coy123** [comment]
We ran all the broken links again through the linkchecker and we have healthier results now.
For reference the 404 results for both of the collections are now:
LINDAT_CLARIN_digital_library_at_the_Institute_of_Formal_and_Applied_Linguistics_UFAL_Faculty_of_Mathematics_and_Physics_Charles_University = 47
Slovenian_language_resource_repository_CLARIN_SI = 4
and the couple of links I checked from the lists really return 404.
