### ISSUE TITLE
Link checker: detect federated login

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#41]
Links that ultimately redirect to the CLARIN discovery service can be considered to have restricted access, even though the response will consist out of a series of redirects ending up with a 200 at discovery.clarin.eu.

**Comment by coy123** [comment]
This is already implemented. The list is to be found here: https://github.com/clarin-eric/login-pages/

This info needs to be disseminated to Clarin Centres...

**Comment by wowasa** [comment]
in fact the issue is at the wrong place here. It is integrated in linkchecker. (see https://github.com/clarin-eric/linkchecker/blob/master/src/main/java/at/ac/oeaw/acdh/stormychecker/config/Configuration.java, line 41). Unfortunately as a hard coded url. 

However, if category depends on other items than status code, the category is no redundant information and we must keep it in the status table - means I have to change the new database model to keep category info in status table

**Comment by twagoo** [comment]
> in fact the issue is at the wrong place here. It is integrated in linkchecker.
For reference: https://github.com/clarin-eric/linkchecker/issues/9
