### ISSUE TITLE
Link Checker: Status 307 with dubious info

### ISSUE THREAD

**Issue by teoric** [clarin-eric/clarin-curation-module#52]
Consider: <https://curate.acdh.oeaw.ac.at/statistics/IDS_Repository/307>; the first link is:
<http://hdl.handle.net/10932/00-03FE-203B-D2BD-4801-9>, which currently gives the following information:

```
Message: HTTP entity too large to be buffered in memory
Expected Content Type:
Content Type: text/html;charset=utf-8
Byte Size: 0
Request Duration(ms): 36
Method: N/A
Timestamp: 2020-03-04 17:20:59.0
```

This information is dubious:

- The message about download size looks like an error encountered by the repository, but it seems to be have occurred inside the checker; it is possible to download the file.
- (Byte size is evidently wrong, probably due to the download problem.)
- What information is supposed to go in `Expected Content Type`?  If it nothing expected, state it; otherwise, it looks like an error.
- The `Content Type` is the one provided by the first URL, at the end of the redirect chain `application/zip` is provided.
- `Method` is not helpful.

Maybe it would be possible to modify the checker to report more conspicuously as follows:

```
Message: (No diagnosis performed on content. HTTP entity too large to be buffered in memory)
Expected Content Type: (no expectation)
Content Type: application/zip
Byte Size: N/A, due to download size
Request Duration(ms): 36
Method: <SOMETHING_USEFUL>
Timestamp: 2020-03-04 17:20:59.0
```

For `Content Type`, one might also consider the chain of redirects:

```
Content Type:  ["text/html;charset=utf-8"; NONE; "application/zip"]
```

**Comment by coy123** [comment]
Hello, thanks for reporting.

Firstly, I would like to mention that Method field is not yet implemented, since we migrated the linkchecker to an [implementation of Stormcrawler](https://github.com/acdh-oeaw/stormychecker). The category broken is also a leftover from the migration. Currently we are working on it to change the classification system from status codes to categories (eg: ok, broken, timeout, too many redirects etc.) to make the results clearer and more transparent.

The status code 307 is the last status code Linkchecker received during the redirect before encountering the large download and considering it as broken (because there is a file size limit). This is wrong and should be considered as undetermined, or better yet the link should be checked with a HEAD first (which was the old implementation and why we have the Method field in the first place).

Expected Content Type is extracted from the CMDI Records and not by checking the link. The content type however is caused by the same bug which causes this url to be reported as 307. It was the last content type recieved in the redirects before the large file was encountered and the link was considered broken. So this is definitely wrong and is on our to do list.

**Comment by coy123** [comment]
Hello,

We have recently rolled out the change to the classification system. Please check your collection and the link checking results and give feedback if it works correctly or needs to be improved.

Thanks

**Comment by wowasa** [comment]
since there was no feedback I assume that the issue is solved
