### ISSUE TITLE
Making scores and reports more useful

### ISSUE THREAD

**Issue by denis-arnold** [clarin-eric/clarin-curation-module#53]
The Curation Module provides a lot useful information. The results could benefit from a link to a documentation. Here a number of examples:

1.) The Collection Report gives an “Average Score: xx out of 15”
How is the number 15 motivated? Where can one find what exactly needs to be improved?

2.) The Header Section contains a score per ID. Sometimes it matches the score in CMD Profile Report, sometimes it seems to be a difference of 1 to this score? 
e.g. https://curate.acdh.oeaw.ac.at/collection/IDS_Repository.html
clarin_eu_cr1_p_1455633534543 
Score: 1.65
https://curate.acdh.oeaw.ac.at/profile/clarin_eu_cr1_p_1455633534543.html
Total: 2.65 Max: 3.00
Could this be an error or does the score in the Collection report refer to a different score? If so what score?

3.) To improve usefulness, more information on which entries or concepts are linked to facets and how/why would be very helpful.

e.g. How is the relation between the facets found in the Curation Module and the facets in this tool:
https://cmdi.clarin.eu/mapping/index.html#mapping

4.) A partial documentation of Cmd Component Section and Cmd Concept Section can be found in the specification: https://office.clarin.eu/v/CE-2016-0742-CLARINPLUS-D2_1.pdf but it would be much more comfortable to get the information on one page describing all features of the report.

**Comment by coy123** [comment]
Hello Denis,

firstly sorry for the late answer. It seems I can't get my notification settings in order. Here are the answers to your questions:

1.) Total score is just an aggregation of all record scores in the collection. Average Score is total score divided by the number of files in the collection. xx out of 15 is the maximum an record can score. Since total score is the aggregation of all record score, the improvement needs to be made on a record level.

You can also validate single records in curation module in the main page(validator button on the left). There you can either upload a record or type in the URL of it. The record report gives more fleshed out descriptions and gives what section scored what and also the issues with the record.

Unfortunately there is no easy way to see record reports from the collection reports, since we don't save each one separately. We save it, if you validate through the validator form for 24 hours (you can change something and upload again which will be regarded as a new record but if you give a URL the report will stay the same until deleted).

2.) It seems this is a bug. I will fix it but it might take a little while until it gets deployed to production. I will let you know in this issue.

3.) As I mentioned above, you can validate single records and in each record report, there is a facets section which might be what you are looking for.

4.) This is a great idea and gets right into my backlog. It will probably in a form of a small question mark next to each section with an explanation when you hover over it. The document you linked is not that actual anymore, so I hope these explanations will be enough.

Cheers

**Comment by wowasa** [comment]
Just a late comment from my side on scoring: scores are calculated differently for profiles and instances (see my brief comment on issue #59).  Programmatically there is no bug but we have to discuss if it makes sense to have a higher possible section score for an instance than for its profile and we have to discuss scoring in general.

**Comment by twagoo** [comment]
Although there may be bugs or not, I think the main issue to address is that of opaqueness of the score calculations. One currently has to look into the code to find out exactly how certain scores were obtained. In my opinion it would be very helpful to make this much more transparent to the users of the curation module. Perhaps it would be good idea to create a new dedicated issue for this.

Based on what you say @wowasa, I would close #59.

**Comment by wowasa** [comment]
I'm closing this issue with regard to my addition in issue #58
