### ISSUE TITLE
Collection Header section score and profile report score don't match

### ISSUE THREAD

**Issue by coy123** [clarin-eric/clarin-curation-module#59]
It is first mentioned here: https://github.com/clarin-eric/clarin-curation-module/issues/53
```
2.) The Header Section contains a score per ID. Sometimes it matches the score in CMD Profile Report, sometimes it seems to be a difference of 1 to this score?
e.g. https://curate.acdh.oeaw.ac.at/collection/IDS_Repository.html
clarin_eu_cr1_p_1455633534543
Score: 1.65
https://curate.acdh.oeaw.ac.at/profile/clarin_eu_cr1_p_1455633534543.html
Total: 2.65 Max: 3.00
Could this be an error or does the score in the Collection report refer to a different score? If so what score?
```

This seems to be a bug. In fact it seems, in collection header section, it is one less than profile report score. So somewhere an extra 1 point is being added.

**Comment by wowasa** [comment]
This is not a bug, at least not a programming bug, since scores are calculated differently in profiles and instances. While in profiles the score can be either 0 or 1, depending on the fact is the profile header is public, in instances the score can have values between 0 to 5, depending on the question if a schema is available (1), if the schema is in component registry (2), if there is a valid mdprofile (3), a mdcollectiondisplayname (4) and a mdselflink (5).

**Comment by wowasa** [comment]
we're going to discuss scoring and will explain it later, but it's not a bug
