### ISSUE TITLE
Database redesign

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/clarin-curation-module#85]
![image](https://user-images.githubusercontent.com/7011396/118773571-a4388880-b88d-11eb-8065-09b587c472f2.png)

**Comment by wowasa** [comment]
I assume the redesign of the database to be a rasa task, since neither curation nor the linkchecker mind the exact database model. But the fact the a URL can occur in different contexts is going to be reflected in rasa-api 3.1, which has necessarily an impact of the to DAO objects LinkToBeChecked. 
The creation script for for the new database model will be in the mysql implementation of rasa

**Comment by wowasa** [comment]
new db design:

![linkchecker-dbmodel_2021-05-24](https://user-images.githubusercontent.com/28445631/119356234-7d6fbd00-bca6-11eb-9010-56783a563458.png)

**Comment by wowasa** [comment]
in fact it's a rasa issue but it's done in v. 5.1.0 with implementation of rasa 4.0.0
